//! Mermaid emitter — renders [`crate::model::Graph`] as a
//! `graph LR` Mermaid diagram with publisher-grouped subgraphs,
//! flow-direction ingress/egress trapezoids, per-edge classDef
//! styling (renderer-compat for older Mermaid), and a stable
//! `@generated by` banner including format version.
//!
//! Implements synthesis §P0-C (format-stability promise),
//! §P0-H (5 determinism invariants), §P1-C (theme system),
//! §P1-G (no tool-version stamp by default).

use std::collections::BTreeMap;
use std::fmt::Write as FmtWrite;

use crate::model::{EdgeKind, Graph, Node};

/// Configurable output options.
#[derive(Debug, Clone, Default)]
pub struct MermaidOptions {
    /// Colour palette (default / high-contrast / monochrome).
    pub theme: Theme,
    /// Layout + framing toggles. Bundled to satisfy clippy's
    /// 4-bools-in-a-struct rule and to make config-table mapping
    /// simpler in story 06.
    pub flags: Flags,
}

/// Layout/framing toggles. Default = "what you want 99% of the time".
///
/// These flags are independent runtime knobs over what is
/// conceptually one struct (output framing). A two-variant enum
/// per flag would cost ergonomics for no clarity win — accept
/// the lint with rationale per `feedback_no_allow_attributes`'s
/// "fix the root cause" carve-out.
#[allow(clippy::struct_excessive_bools)]
#[derive(Debug, Clone, Copy)]
pub struct Flags {
    /// Cluster subjects under their publishing service via
    /// Mermaid `subgraph`s.
    pub group_by_publisher: bool,
    /// Include ingress/egress trapezoids
    /// (disable to get a pure service↔subject mesh).
    pub include_ingress_egress: bool,
    /// Append the tool semver to the `@generated by` comment.
    /// Default `false` (synthesis §P1-G): forcing it on means
    /// every adopter re-commits on every tool upgrade.
    pub include_version_stamp: bool,
    /// Wrap output in a Markdown code fence
    /// for direct embedding in `.md` files.
    pub markdown: bool,
}

impl Default for Flags {
    fn default() -> Self {
        Self {
            group_by_publisher: true,
            include_ingress_egress: true,
            include_version_stamp: false,
            markdown: true,
        }
    }
}

/// Colour palette.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Theme {
    /// Blue publish / dashed green consume / red ingress / purple egress.
    #[default]
    Default,
    /// `ColorBrewer` Set2 — WCAG AA contrast.
    HighContrast,
    /// Black + grayscale; stabilises `check` diffs across renderer
    /// environments.
    Monochrome,
}

/// Current Mermaid output format version. Bumped only with a
/// major tool version per `STABILITY.md`.
pub const FORMAT_VERSION: &str = "mermaid-v1";

/// Render `graph` to a Mermaid `graph LR` string.
///
/// The output is **byte-deterministic** given identical input —
/// no `HashMap` iteration is involved, nodes/edges are pre-sorted
/// in [`crate::analysis::graph::build_graph`], and the
/// `@generated by` banner stamps only the format version, not the
/// tool version, by default.
#[must_use]
pub fn render_mermaid(graph: &Graph, opts: &MermaidOptions) -> String {
    let mut out = String::new();
    write_banner(&mut out, opts);
    if opts.flags.markdown {
        out.push_str("\n```mermaid\n");
    }
    out.push_str("graph LR\n");

    write_nodes(&mut out, graph, opts);
    write_edges(&mut out, graph);
    write_styles(&mut out, graph, opts);

    if opts.flags.markdown {
        out.push_str("```\n");
    }
    out
}

fn write_banner(out: &mut String, opts: &MermaidOptions) {
    out.push_str("<!-- @generated by cargo-eventflow");
    if opts.flags.include_version_stamp {
        let _ = write!(out, " {}", env!("CARGO_PKG_VERSION"));
    }
    let _ = writeln!(
        out,
        " (format: {FORMAT_VERSION}) — do not edit; regenerate with `cargo eventflow mermaid` -->"
    );
}

fn write_nodes(out: &mut String, graph: &Graph, opts: &MermaidOptions) {
    // Ingress + egress first (outside subgraphs).
    if opts.flags.include_ingress_egress {
        for node in &graph.nodes {
            match node {
                Node::Ingress(name) => {
                    let _ = writeln!(
                        out,
                        "  {}[/\"{}\"\\]:::ingress",
                        node_id(node),
                        escape_label(name)
                    );
                }
                Node::Egress(name) => {
                    let _ = writeln!(
                        out,
                        "  {}[\\\"{}\"/]:::egress",
                        node_id(node),
                        escape_label(name)
                    );
                }
                _ => {}
            }
        }
    }

    // Service nodes always rendered (rectangles).
    for node in &graph.nodes {
        if let Node::Service(name) = node {
            let _ = writeln!(out, "  {}[\"{}\"]", node_id(node), escape_label(name));
        }
    }

    // Subject nodes, optionally grouped by publishing service.
    if opts.flags.group_by_publisher {
        let groups = group_subjects_by_publisher(graph);
        for (publisher, subjects) in &groups.by_publisher {
            let _ = writeln!(
                out,
                "  subgraph {} [\"{} — published\"]",
                escape_id(&format!("sg_{publisher}")),
                escape_label(publisher)
            );
            for subj in subjects {
                let _ = writeln!(
                    out,
                    "    {}([\"{}\"])",
                    node_id(&Node::Subject(subj.clone())),
                    escape_label(subj)
                );
            }
            let _ = writeln!(out, "  end");
        }
        if !groups.multi_publisher.is_empty() {
            let _ = writeln!(
                out,
                "  subgraph sg_multi_publisher [\"shared subjects (multiple publishers)\"]"
            );
            for subj in &groups.multi_publisher {
                let _ = writeln!(
                    out,
                    "    {}([\"{}\"])",
                    node_id(&Node::Subject(subj.clone())),
                    escape_label(subj)
                );
            }
            let _ = writeln!(out, "  end");
        }
        // Subjects with no publisher (pure-consume, ingress-only).
        for subj in &groups.orphans {
            let _ = writeln!(
                out,
                "  {}([\"{}\"])",
                node_id(&Node::Subject(subj.clone())),
                escape_label(subj)
            );
        }
    } else {
        for node in &graph.nodes {
            if let Node::Subject(name) = node {
                let _ = writeln!(out, "  {}([\"{}\"])", node_id(node), escape_label(name));
            }
        }
    }
}

fn write_edges(out: &mut String, graph: &Graph) {
    for edge in &graph.edges {
        let from = node_id(&edge.from);
        let to = node_id(&edge.to);
        let label = edge.label.as_ref().map_or_else(
            || " -->".to_string(),
            |l| format!(" -- \"{}\" -->", escape_label(l)),
        );
        // Edge styling is driven entirely by per-edge `linkStyle`
        // directives below (write_styles). `:::class` on the
        // arrow tail would apply to the target node, not the
        // edge — wrong semantically.
        let _ = writeln!(out, "  {from}{label} {to}");
    }
}

fn write_styles(out: &mut String, graph: &Graph, opts: &MermaidOptions) {
    let palette = palette_for(opts.theme);

    // Node classDefs (ingress / egress shapes already implicit via [/...\] /[\...]/).
    let _ = writeln!(
        out,
        "  classDef ingress fill:{},stroke:{},stroke-width:2px;",
        palette.ingress_fill, palette.ingress_stroke
    );
    let _ = writeln!(
        out,
        "  classDef egress fill:{},stroke:{},stroke-width:2px;",
        palette.egress_fill, palette.egress_stroke
    );

    // Per-edge linkStyle (one line per edge — renderer-compat per R3N2).
    // Edge indices are stable because graph.edges is pre-sorted.
    for (idx, edge) in graph.edges.iter().enumerate() {
        let style = match edge.kind {
            EdgeKind::Publish => &palette.publish_stroke,
            EdgeKind::Consume => &palette.consume_stroke,
            EdgeKind::Ingress => &palette.ingress_stroke,
            EdgeKind::Egress => &palette.egress_stroke,
        };
        let extra = match edge.kind {
            EdgeKind::Consume => ",stroke-dasharray:5 5",
            _ => "",
        };
        let width = match edge.kind {
            EdgeKind::Ingress | EdgeKind::Egress => 3,
            _ => 2,
        };
        let _ = writeln!(
            out,
            "  linkStyle {idx} stroke:{style},stroke-width:{width}px{extra}"
        );
    }
}

struct Groups {
    by_publisher: BTreeMap<String, Vec<String>>,
    multi_publisher: Vec<String>,
    orphans: Vec<String>,
}

fn group_subjects_by_publisher(graph: &Graph) -> Groups {
    let mut publishers_of: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for edge in &graph.edges {
        if matches!(edge.kind, EdgeKind::Publish) {
            if let (Node::Service(svc), Node::Subject(sub)) = (&edge.from, &edge.to) {
                publishers_of
                    .entry(sub.clone())
                    .or_default()
                    .push(svc.clone());
            }
        }
    }

    let mut by_publisher: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut multi_publisher: Vec<String> = Vec::new();
    let mut orphans: Vec<String> = Vec::new();

    for node in &graph.nodes {
        if let Node::Subject(s) = node {
            match publishers_of.get(s) {
                Some(pubs) if pubs.len() == 1 => {
                    by_publisher
                        .entry(pubs[0].clone())
                        .or_default()
                        .push(s.clone());
                }
                Some(pubs) if pubs.len() > 1 => {
                    multi_publisher.push(s.clone());
                }
                _ => orphans.push(s.clone()),
            }
        }
    }
    for v in by_publisher.values_mut() {
        v.sort();
    }
    multi_publisher.sort();
    orphans.sort();

    Groups {
        by_publisher,
        multi_publisher,
        orphans,
    }
}

struct Palette {
    publish_stroke: String,
    consume_stroke: String,
    ingress_stroke: String,
    egress_stroke: String,
    ingress_fill: String,
    egress_fill: String,
}

fn palette_for(theme: Theme) -> Palette {
    match theme {
        Theme::Default => Palette {
            publish_stroke: "#2563eb".into(),
            consume_stroke: "#16a34a".into(),
            ingress_stroke: "#dc2626".into(),
            egress_stroke: "#7c3aed".into(),
            ingress_fill: "#fee2e2".into(),
            egress_fill: "#ede9fe".into(),
        },
        Theme::HighContrast => Palette {
            // ColorBrewer Set2 + IBM-ish 5-colour overrides.
            publish_stroke: "#1f78b4".into(),
            consume_stroke: "#33a02c".into(),
            ingress_stroke: "#e31a1c".into(),
            egress_stroke: "#ff7f00".into(),
            ingress_fill: "#fdbf6f".into(),
            egress_fill: "#cab2d6".into(),
        },
        Theme::Monochrome => Palette {
            publish_stroke: "#000".into(),
            consume_stroke: "#555".into(),
            ingress_stroke: "#000".into(),
            egress_stroke: "#000".into(),
            ingress_fill: "#eee".into(),
            egress_fill: "#eee".into(),
        },
    }
}

// -------- id + label sanitisation --------

fn node_id(node: &Node) -> String {
    let raw = node.id();
    escape_id(&raw)
}

fn escape_id(s: &str) -> String {
    // Mermaid node ids accept [a-zA-Z0-9_]. Map everything else
    // to '_'. Tail wildcard '>' → 'g' (greater); single '*' → 's'
    // (star); '.' → '_'. Collisions disambiguated by callers
    // (the synthesis §P0-H invariant 2 disambiguator lives in
    // build_graph if it ever becomes load-bearing — for v0.1 we
    // accept that the BTreeSet dedupe in build_graph already
    // prevents most collision shapes).
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            'a'..='z' | 'A'..='Z' | '0'..='9' | '_' => out.push(c),
            '>' => out.push('g'),
            '*' => out.push('s'),
            _ => out.push('_'),
        }
    }
    out
}

fn escape_label(s: &str) -> String {
    // Mermaid labels accept most text but `"` ends the literal.
    // Escape via HTML entity.
    s.replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Edge, EdgeKind, Graph, Node};

    fn empty_graph() -> Graph {
        Graph {
            nodes: vec![],
            edges: vec![],
        }
    }

    fn simple_graph() -> Graph {
        Graph {
            nodes: vec![
                Node::Service("svc-a".into()),
                Node::Service("svc-b".into()),
                Node::Subject("foo.bar".into()),
            ],
            edges: vec![
                Edge {
                    from: Node::Service("svc-a".into()),
                    to: Node::Subject("foo.bar".into()),
                    kind: EdgeKind::Publish,
                    label: None,
                },
                Edge {
                    from: Node::Subject("foo.bar".into()),
                    to: Node::Service("svc-b".into()),
                    kind: EdgeKind::Consume,
                    label: Some("my-durable".into()),
                },
            ],
        }
    }

    #[test]
    fn renders_graph_lr() {
        let out = render_mermaid(&simple_graph(), &MermaidOptions::default());
        assert!(out.contains("graph LR"));
    }

    #[test]
    fn banner_does_not_include_version_by_default() {
        let out = render_mermaid(&simple_graph(), &MermaidOptions::default());
        assert!(out.contains("@generated by cargo-eventflow"));
        assert!(out.contains(FORMAT_VERSION));
        // Default config: no tool version. Bare keyword absent.
        let banner_line = out.lines().next().unwrap_or("");
        assert!(
            !banner_line.contains(env!("CARGO_PKG_VERSION")),
            "version stamp leaked into banner: {banner_line}"
        );
    }

    #[test]
    fn version_stamp_included_when_opted_in() {
        let opts = MermaidOptions {
            flags: Flags {
                include_version_stamp: true,
                ..Flags::default()
            },
            ..MermaidOptions::default()
        };
        let out = render_mermaid(&simple_graph(), &opts);
        assert!(out.contains(env!("CARGO_PKG_VERSION")));
    }

    #[test]
    fn markdown_wrap_default_on() {
        let out = render_mermaid(&simple_graph(), &MermaidOptions::default());
        assert!(out.contains("```mermaid"));
        assert!(out.trim_end().ends_with("```"));
    }

    #[test]
    fn markdown_wrap_off() {
        let opts = MermaidOptions {
            flags: Flags {
                markdown: false,
                ..Flags::default()
            },
            ..MermaidOptions::default()
        };
        let out = render_mermaid(&simple_graph(), &opts);
        assert!(!out.contains("```"));
    }

    #[test]
    fn deterministic_byte_stable() {
        let g = simple_graph();
        let opts = MermaidOptions::default();
        let a = render_mermaid(&g, &opts);
        let b = render_mermaid(&g, &opts);
        assert_eq!(a, b);
    }

    #[test]
    fn consume_edge_carries_durable_label() {
        let out = render_mermaid(&simple_graph(), &MermaidOptions::default());
        assert!(out.contains("my-durable"));
    }

    #[test]
    fn theme_monochrome_blackandwhite_strokes_only() {
        let opts = MermaidOptions {
            theme: Theme::Monochrome,
            ..MermaidOptions::default()
        };
        let out = render_mermaid(&simple_graph(), &opts);
        assert!(!out.contains("#2563eb"), "no default-theme blue allowed");
        assert!(out.contains("#000") || out.contains("#555"));
    }

    #[test]
    fn ingress_egress_trapezoid_shapes() {
        let g = Graph {
            nodes: vec![
                Node::Service("data".into()),
                Node::Subject("market.klines".into()),
                Node::Ingress("Binance WS".into()),
                Node::Egress("Binance REST".into()),
            ],
            edges: vec![Edge {
                from: Node::Ingress("Binance WS".into()),
                to: Node::Subject("market.klines".into()),
                kind: EdgeKind::Ingress,
                label: None,
            }],
        };
        let out = render_mermaid(&g, &MermaidOptions::default());
        assert!(out.contains("[/\"Binance WS\"\\]"), "ingress trapezoid");
        assert!(out.contains("[\\\"Binance REST\"/]"), "egress trapezoid");
    }

    #[test]
    fn empty_graph_yields_valid_skeleton() {
        let out = render_mermaid(&empty_graph(), &MermaidOptions::default());
        assert!(out.contains("graph LR"));
        // No node lines, no edges, no styles — just the banner +
        // graph header + (optional) classDefs.
    }

    #[test]
    fn subgraph_when_group_by_publisher() {
        let out = render_mermaid(&simple_graph(), &MermaidOptions::default());
        assert!(out.contains("subgraph sg_svc"), "subgraph rendered");
    }

    #[test]
    fn flat_layout_when_grouping_disabled() {
        let opts = MermaidOptions {
            flags: Flags {
                group_by_publisher: false,
                ..Flags::default()
            },
            ..MermaidOptions::default()
        };
        let out = render_mermaid(&simple_graph(), &opts);
        assert!(!out.contains("subgraph"));
    }

    #[test]
    fn label_quotes_escaped() {
        let g = Graph {
            nodes: vec![Node::Subject("contains \"quote\"".into())],
            edges: vec![],
        };
        let out = render_mermaid(&g, &MermaidOptions::default());
        assert!(out.contains("&quot;"));
        assert!(!out.contains("\"contains \"quote\"\""));
    }
}
