//! Mermaid emitter — renders [`crate::model::Graph`] as a
//! `graph LR` Mermaid diagram with publisher-grouped subgraphs,
//! flow-direction ingress/egress trapezoids, per-edge classDef
//! styling (renderer-compat for older Mermaid), and a stable
//! `@generated by` banner including format version.
//!
//! Implements synthesis §P0-C (format-stability promise),
//! §P0-H (5 determinism invariants), §P1-C (theme system),
//! §P1-G (no tool-version stamp by default).

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as FmtWrite;

use crate::model::{EdgeKind, Graph, Node};

/// Configurable output options.
#[derive(Debug, Clone, Default)]
pub struct MermaidOptions {
    /// Colour palette (default / high-contrast / monochrome).
    pub theme: Theme,
    /// Layout + framing toggles. Bundled to satisfy clippy's
    /// 4-bools-in-a-struct rule and to make config-table mapping
    /// simpler in story 06.
    pub flags: Flags,
}

/// Layout/framing toggles. Default = "what you want 99% of the time".
///
/// These flags are independent runtime knobs over what is
/// conceptually one struct (output framing). A two-variant enum
/// per flag would cost ergonomics for no clarity win — accept
/// the lint with rationale per `feedback_no_allow_attributes`'s
/// "fix the root cause" carve-out.
#[allow(clippy::struct_excessive_bools)]
#[derive(Debug, Clone, Copy)]
pub struct Flags {
    /// Cluster subjects under their publishing service via
    /// Mermaid `subgraph`s.
    pub group_by_publisher: bool,
    /// Include ingress/egress trapezoids
    /// (disable to get a pure service↔subject mesh).
    pub include_ingress_egress: bool,
    /// Append the tool semver to the `@generated by` comment.
    /// Default `false` (synthesis §P1-G): forcing it on means
    /// every adopter re-commits on every tool upgrade.
    pub include_version_stamp: bool,
    /// Wrap output in a Markdown code fence
    /// for direct embedding in `.md` files.
    pub markdown: bool,
}

impl Default for Flags {
    fn default() -> Self {
        Self {
            group_by_publisher: true,
            include_ingress_egress: true,
            include_version_stamp: false,
            markdown: true,
        }
    }
}

/// Colour palette.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Theme {
    /// Blue publish / dashed green consume / red ingress / purple egress.
    #[default]
    Default,
    /// `ColorBrewer` Set2 — WCAG AA contrast.
    HighContrast,
    /// Black + grayscale; stabilises `check` diffs across renderer
    /// environments.
    Monochrome,
}

/// Current Mermaid output format version. Bumped only with a
/// major tool version per `STABILITY.md`.
pub const FORMAT_VERSION: &str = "mermaid-v1";

/// Render `graph` to a Mermaid `graph LR` string.
///
/// The output is **byte-deterministic** given identical input —
/// no `HashMap` iteration is involved, nodes/edges are pre-sorted
/// in [`crate::analysis::graph::build_graph`], and the
/// `@generated by` banner stamps only the format version, not the
/// tool version, by default.
#[must_use]
pub fn render_mermaid(graph: &Graph, opts: &MermaidOptions) -> String {
    let ids = IdMap::build(graph);

    let mut out = String::new();
    if opts.flags.markdown {
        out.push_str("```mermaid\n");
    }
    write_banner(&mut out, opts);
    out.push_str("graph LR\n");

    write_nodes(&mut out, graph, opts, &ids);
    write_edges(&mut out, graph, &ids);
    write_styles(&mut out, graph, opts);

    if opts.flags.markdown {
        out.push_str("```\n");
    }
    out
}

/// Emit the `@generated by` banner as a Mermaid `%%` comment.
///
/// Putting it inside the diagram body (and inside the
/// Markdown code fence when markdown-wrapped) means renderers
/// that consume the file directly (`mmdc`, Mermaid Live Editor,
/// Markdown previewers that pre-extract the fence) all see a
/// valid Mermaid program starting with `%%`-comment + `graph LR`,
/// not an `UnknownDiagramError` from an HTML comment at offset 0.
///
/// `check` mode still recovers the format version by grepping for
/// the `%% @generated` line — see `STABILITY.md`.
fn write_banner(out: &mut String, opts: &MermaidOptions) {
    out.push_str("%% @generated by cargo-eventflow");
    if opts.flags.include_version_stamp {
        let _ = write!(out, " {}", env!("CARGO_PKG_VERSION"));
    }
    let _ = writeln!(
        out,
        " (format: {FORMAT_VERSION}) — do not edit; regenerate with `cargo eventflow mermaid`"
    );
}

fn write_nodes(out: &mut String, graph: &Graph, opts: &MermaidOptions, ids: &IdMap) {
    // Ingress + egress first (outside subgraphs).
    if opts.flags.include_ingress_egress {
        for node in &graph.nodes {
            match node {
                Node::Ingress(name) => {
                    let _ = writeln!(
                        out,
                        "  {}[/\"{}\"\\]:::ingress",
                        ids.for_node(node),
                        escape_label(name)
                    );
                }
                Node::Egress(name) => {
                    let _ = writeln!(
                        out,
                        "  {}[\\\"{}\"/]:::egress",
                        ids.for_node(node),
                        escape_label(name)
                    );
                }
                _ => {}
            }
        }
    }

    // Service nodes always rendered (rectangles).
    for node in &graph.nodes {
        if let Node::Service(name) = node {
            let _ = writeln!(out, "  {}[\"{}\"]", ids.for_node(node), escape_label(name));
        }
    }

    // Subject nodes, optionally grouped by publishing service.
    if opts.flags.group_by_publisher {
        let groups = group_subjects_by_publisher(graph);
        for (publisher, subjects) in &groups.by_publisher {
            let _ = writeln!(
                out,
                "  subgraph {} [\"{} — published\"]",
                ids.for_subgraph(publisher),
                escape_label(publisher)
            );
            for subj in subjects {
                let _ = writeln!(
                    out,
                    "    {}([\"{}\"])",
                    ids.for_node(&Node::Subject(subj.clone())),
                    escape_label(subj)
                );
            }
            let _ = writeln!(out, "  end");
        }
        if !groups.multi_publisher.is_empty() {
            let _ = writeln!(
                out,
                "  subgraph {} [\"shared subjects (multiple publishers)\"]",
                ids.for_subgraph_special_multi()
            );
            for subj in &groups.multi_publisher {
                let _ = writeln!(
                    out,
                    "    {}([\"{}\"])",
                    ids.for_node(&Node::Subject(subj.clone())),
                    escape_label(subj)
                );
            }
            let _ = writeln!(out, "  end");
        }
        // Subjects with no publisher (pure-consume, ingress-only).
        for subj in &groups.orphans {
            let _ = writeln!(
                out,
                "  {}([\"{}\"])",
                ids.for_node(&Node::Subject(subj.clone())),
                escape_label(subj)
            );
        }
    } else {
        for node in &graph.nodes {
            if let Node::Subject(name) = node {
                let _ = writeln!(
                    out,
                    "  {}([\"{}\"])",
                    ids.for_node(node),
                    escape_label(name)
                );
            }
        }
    }
}

fn write_edges(out: &mut String, graph: &Graph, ids: &IdMap) {
    for edge in &graph.edges {
        let from = ids.for_node(&edge.from);
        let to = ids.for_node(&edge.to);
        let label = edge.label.as_ref().map_or_else(
            || " -->".to_string(),
            |l| format!(" -- \"{}\" -->", escape_label(l)),
        );
        let _ = writeln!(out, "  {from}{label} {to}");
    }
}

fn write_styles(out: &mut String, graph: &Graph, opts: &MermaidOptions) {
    let palette = palette_for(opts.theme);

    // Node classDefs (ingress / egress shapes already implicit via [/...\] /[\...]/).
    let _ = writeln!(
        out,
        "  classDef ingress fill:{},stroke:{},stroke-width:2px;",
        palette.ingress_fill, palette.ingress_stroke
    );
    let _ = writeln!(
        out,
        "  classDef egress fill:{},stroke:{},stroke-width:2px;",
        palette.egress_fill, palette.egress_stroke
    );

    // Per-edge linkStyle (one line per edge — renderer-compat per R3N2).
    // Edge indices are stable because graph.edges is pre-sorted.
    for (idx, edge) in graph.edges.iter().enumerate() {
        let style = match edge.kind {
            EdgeKind::Publish => &palette.publish_stroke,
            EdgeKind::Consume => &palette.consume_stroke,
            EdgeKind::Ingress => &palette.ingress_stroke,
            EdgeKind::Egress => &palette.egress_stroke,
        };
        let extra = match edge.kind {
            EdgeKind::Consume => ",stroke-dasharray:5 5",
            _ => "",
        };
        let width = match edge.kind {
            EdgeKind::Ingress | EdgeKind::Egress => 3,
            _ => 2,
        };
        let _ = writeln!(
            out,
            "  linkStyle {idx} stroke:{style},stroke-width:{width}px{extra}"
        );
    }
}

struct Groups {
    by_publisher: BTreeMap<String, Vec<String>>,
    multi_publisher: Vec<String>,
    orphans: Vec<String>,
}

fn group_subjects_by_publisher(graph: &Graph) -> Groups {
    let mut publishers_of: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for edge in &graph.edges {
        if matches!(edge.kind, EdgeKind::Publish) {
            if let (Node::Service(svc), Node::Subject(sub)) = (&edge.from, &edge.to) {
                publishers_of
                    .entry(sub.clone())
                    .or_default()
                    .push(svc.clone());
            }
        }
    }

    let mut by_publisher: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut multi_publisher: Vec<String> = Vec::new();
    let mut orphans: Vec<String> = Vec::new();

    for node in &graph.nodes {
        if let Node::Subject(s) = node {
            match publishers_of.get(s) {
                Some(pubs) if pubs.len() == 1 => {
                    by_publisher
                        .entry(pubs[0].clone())
                        .or_default()
                        .push(s.clone());
                }
                Some(pubs) if pubs.len() > 1 => {
                    multi_publisher.push(s.clone());
                }
                _ => orphans.push(s.clone()),
            }
        }
    }
    for v in by_publisher.values_mut() {
        v.sort();
    }
    multi_publisher.sort();
    orphans.sort();

    Groups {
        by_publisher,
        multi_publisher,
        orphans,
    }
}

struct Palette {
    publish_stroke: String,
    consume_stroke: String,
    ingress_stroke: String,
    egress_stroke: String,
    ingress_fill: String,
    egress_fill: String,
}

fn palette_for(theme: Theme) -> Palette {
    match theme {
        Theme::Default => Palette {
            publish_stroke: "#2563eb".into(),
            consume_stroke: "#16a34a".into(),
            ingress_stroke: "#dc2626".into(),
            egress_stroke: "#7c3aed".into(),
            ingress_fill: "#fee2e2".into(),
            egress_fill: "#ede9fe".into(),
        },
        Theme::HighContrast => Palette {
            // ColorBrewer Set2 + IBM-ish 5-colour overrides.
            publish_stroke: "#1f78b4".into(),
            consume_stroke: "#33a02c".into(),
            ingress_stroke: "#e31a1c".into(),
            egress_stroke: "#ff7f00".into(),
            ingress_fill: "#fdbf6f".into(),
            egress_fill: "#cab2d6".into(),
        },
        Theme::Monochrome => Palette {
            publish_stroke: "#000".into(),
            consume_stroke: "#555".into(),
            ingress_stroke: "#000".into(),
            egress_stroke: "#000".into(),
            ingress_fill: "#eee".into(),
            egress_fill: "#eee".into(),
        },
    }
}

// -------- id + label sanitisation --------

/// Collision-free Mermaid-ID map for every node + subgraph in the graph.
///
/// Built once per render pass. Maps each raw key (`Node::id()` for nodes,
/// `sg:<service>` for publisher subgraphs) to a Mermaid-safe identifier
/// that is **guaranteed unique** within the diagram.
///
/// Why a two-pass map and not inline escape: the naive escape collapses
/// `>` → `g`, `*` → `s`, `.` → `_`. Two distinct raw keys can collapse
/// to the same Mermaid id (`risk.events.*` and `risk.events.s` both
/// become `sub_risk_events_s`). The map detects that collision and
/// appends a numeric suffix (`_2`, `_3`, …) to the second-and-later
/// occurrences in canonical raw-key order.
struct IdMap {
    map: BTreeMap<String, String>,
}

impl IdMap {
    /// Collect every raw id that will appear in the rendered diagram
    /// (node ids + publisher-subgraph ids + the special multi-publisher
    /// subgraph id) and assign each a Mermaid-safe, collision-free id.
    fn build(graph: &Graph) -> Self {
        let mut raw_ids: BTreeSet<String> = BTreeSet::new();
        for node in &graph.nodes {
            raw_ids.insert(node.id());
        }
        for edge in &graph.edges {
            if matches!(edge.kind, EdgeKind::Publish) {
                if let Node::Service(svc) = &edge.from {
                    raw_ids.insert(format!("sg:{svc}"));
                }
            }
        }
        raw_ids.insert(MULTI_PUBLISHER_RAW.to_string());

        let mut map = BTreeMap::new();
        let mut used: BTreeSet<String> = BTreeSet::new();
        for raw in raw_ids {
            let base = escape_id_basic(&raw);
            let mut candidate = base.clone();
            let mut suffix: usize = 2;
            while used.contains(&candidate) {
                candidate = format!("{base}_{suffix}");
                suffix += 1;
            }
            used.insert(candidate.clone());
            map.insert(raw, candidate);
        }
        Self { map }
    }

    fn for_node(&self, node: &Node) -> &str {
        self.lookup(&node.id())
    }

    fn for_subgraph(&self, service: &str) -> &str {
        self.lookup(&format!("sg:{service}"))
    }

    fn for_subgraph_special_multi(&self) -> &str {
        self.lookup(MULTI_PUBLISHER_RAW)
    }

    fn lookup(&self, raw: &str) -> &str {
        self.map
            .get(raw)
            .map_or(MISSING_ID_SENTINEL, String::as_str)
    }
}

const MULTI_PUBLISHER_RAW: &str = "sg:__multi_publisher__";
const MISSING_ID_SENTINEL: &str = "_missing_id_";

/// Map a raw key to a Mermaid-safe character set. Does not handle
/// collisions on its own — that's [`IdMap::build`]'s job.
fn escape_id_basic(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            'a'..='z' | 'A'..='Z' | '0'..='9' | '_' => out.push(c),
            '>' => out.push('g'),
            '*' => out.push('s'),
            _ => out.push('_'),
        }
    }
    out
}

fn escape_label(s: &str) -> String {
    // Mermaid labels accept most text but `"` ends the literal.
    // Escape via HTML entity.
    s.replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Edge, EdgeKind, Graph, Node};

    fn empty_graph() -> Graph {
        Graph {
            nodes: vec![],
            edges: vec![],
        }
    }

    fn simple_graph() -> Graph {
        Graph {
            nodes: vec![
                Node::Service("svc-a".into()),
                Node::Service("svc-b".into()),
                Node::Subject("foo.bar".into()),
            ],
            edges: vec![
                Edge {
                    from: Node::Service("svc-a".into()),
                    to: Node::Subject("foo.bar".into()),
                    kind: EdgeKind::Publish,
                    label: None,
                },
                Edge {
                    from: Node::Subject("foo.bar".into()),
                    to: Node::Service("svc-b".into()),
                    kind: EdgeKind::Consume,
                    label: Some("my-durable".into()),
                },
            ],
        }
    }

    #[test]
    fn renders_graph_lr() {
        let out = render_mermaid(&simple_graph(), &MermaidOptions::default());
        assert!(out.contains("graph LR"));
    }

    #[test]
    fn banner_does_not_include_version_by_default() {
        let out = render_mermaid(&simple_graph(), &MermaidOptions::default());
        assert!(out.contains("@generated by cargo-eventflow"));
        assert!(out.contains(FORMAT_VERSION));
        // Default config: no tool version. Bare keyword absent.
        let banner_line = out.lines().next().unwrap_or("");
        assert!(
            !banner_line.contains(env!("CARGO_PKG_VERSION")),
            "version stamp leaked into banner: {banner_line}"
        );
    }

    #[test]
    fn version_stamp_included_when_opted_in() {
        let opts = MermaidOptions {
            flags: Flags {
                include_version_stamp: true,
                ..Flags::default()
            },
            ..MermaidOptions::default()
        };
        let out = render_mermaid(&simple_graph(), &opts);
        assert!(out.contains(env!("CARGO_PKG_VERSION")));
    }

    #[test]
    fn markdown_wrap_default_on() {
        let out = render_mermaid(&simple_graph(), &MermaidOptions::default());
        assert!(out.contains("```mermaid"));
        assert!(out.trim_end().ends_with("```"));
    }

    #[test]
    fn markdown_wrap_off() {
        let opts = MermaidOptions {
            flags: Flags {
                markdown: false,
                ..Flags::default()
            },
            ..MermaidOptions::default()
        };
        let out = render_mermaid(&simple_graph(), &opts);
        assert!(!out.contains("```"));
    }

    #[test]
    fn deterministic_byte_stable() {
        let g = simple_graph();
        let opts = MermaidOptions::default();
        let a = render_mermaid(&g, &opts);
        let b = render_mermaid(&g, &opts);
        assert_eq!(a, b);
    }

    #[test]
    fn consume_edge_carries_durable_label() {
        let out = render_mermaid(&simple_graph(), &MermaidOptions::default());
        assert!(out.contains("my-durable"));
    }

    #[test]
    fn theme_monochrome_blackandwhite_strokes_only() {
        let opts = MermaidOptions {
            theme: Theme::Monochrome,
            ..MermaidOptions::default()
        };
        let out = render_mermaid(&simple_graph(), &opts);
        assert!(!out.contains("#2563eb"), "no default-theme blue allowed");
        assert!(out.contains("#000") || out.contains("#555"));
    }

    #[test]
    fn ingress_egress_trapezoid_shapes() {
        let g = Graph {
            nodes: vec![
                Node::Service("data".into()),
                Node::Subject("market.klines".into()),
                Node::Ingress("Binance WS".into()),
                Node::Egress("Binance REST".into()),
            ],
            edges: vec![Edge {
                from: Node::Ingress("Binance WS".into()),
                to: Node::Subject("market.klines".into()),
                kind: EdgeKind::Ingress,
                label: None,
            }],
        };
        let out = render_mermaid(&g, &MermaidOptions::default());
        assert!(out.contains("[/\"Binance WS\"\\]"), "ingress trapezoid");
        assert!(out.contains("[\\\"Binance REST\"/]"), "egress trapezoid");
    }

    #[test]
    fn empty_graph_yields_valid_skeleton() {
        let out = render_mermaid(&empty_graph(), &MermaidOptions::default());
        assert!(out.contains("graph LR"));
        // No node lines, no edges, no styles — just the banner +
        // graph header + (optional) classDefs.
    }

    #[test]
    fn subgraph_when_group_by_publisher() {
        let out = render_mermaid(&simple_graph(), &MermaidOptions::default());
        assert!(out.contains("subgraph sg_svc"), "subgraph rendered");
    }

    #[test]
    fn flat_layout_when_grouping_disabled() {
        let opts = MermaidOptions {
            flags: Flags {
                group_by_publisher: false,
                ..Flags::default()
            },
            ..MermaidOptions::default()
        };
        let out = render_mermaid(&simple_graph(), &opts);
        assert!(!out.contains("subgraph"));
    }

    #[test]
    fn label_quotes_escaped() {
        let g = Graph {
            nodes: vec![Node::Subject("contains \"quote\"".into())],
            edges: vec![],
        };
        let out = render_mermaid(&g, &MermaidOptions::default());
        assert!(out.contains("&quot;"));
        assert!(!out.contains("\"contains \"quote\"\""));
    }

    // ---- disambiguator tests (P1 commit 1) ----
    //
    // The naive escape collapses `*` → `s`, `>` → `g`, `.` → `_`. Two
    // distinct raw keys can collapse to the same id. The disambiguator
    // detects collisions and appends `_2`, `_3`, … in canonical raw-key
    // order so every rendered id is unique.

    fn collision_graph() -> Graph {
        Graph {
            nodes: vec![
                Node::Subject("risk.events.*".into()),
                Node::Subject("risk.events.s".into()),
                Node::Subject("risk.events.>".into()),
                Node::Subject("risk.events.g".into()),
            ],
            edges: vec![],
        }
    }

    #[test]
    fn disambiguator_resolves_star_vs_literal_s_collision() {
        let out = render_mermaid(&collision_graph(), &MermaidOptions::default());
        let lines: Vec<&str> = out.lines().collect();
        // Each subject must appear with its own id; collisions are
        // resolved by `_2` suffix on the second-and-later raw keys in
        // canonical (BTreeSet) order: `sub:risk.events.*`,
        // `sub:risk.events.>`, `sub:risk.events.g`, `sub:risk.events.s`.
        // After disambiguation:
        //   sub:risk.events.*  → sub_risk_events_s
        //   sub:risk.events.>  → sub_risk_events_g
        //   sub:risk.events.g  → sub_risk_events_g_2
        //   sub:risk.events.s  → sub_risk_events_s_2
        let id_lines: Vec<&&str> = lines
            .iter()
            .filter(|l| l.contains("([\"risk.events."))
            .collect();
        assert_eq!(id_lines.len(), 4, "all 4 subject nodes rendered");

        // Extract the rendered Mermaid ids — they must all be distinct.
        let ids: Vec<&str> = id_lines
            .iter()
            .filter_map(|l| l.split('(').next().map(str::trim))
            .collect();
        let unique: BTreeSet<&str> = ids.iter().copied().collect();
        assert_eq!(
            unique.len(),
            ids.len(),
            "disambiguator failed: duplicate ids {ids:?}"
        );

        // Lock the specific suffix pattern so future refactors notice.
        assert!(out.contains("sub_risk_events_s([\"risk.events.*\"])"));
        assert!(out.contains("sub_risk_events_g([\"risk.events.>\"])"));
        assert!(out.contains("sub_risk_events_g_2([\"risk.events.g\"])"));
        assert!(out.contains("sub_risk_events_s_2([\"risk.events.s\"])"));
    }

    #[test]
    fn disambiguator_is_deterministic_across_runs() {
        let g = collision_graph();
        let opts = MermaidOptions::default();
        let a = render_mermaid(&g, &opts);
        let b = render_mermaid(&g, &opts);
        assert_eq!(a, b, "two render passes must be byte-identical");
    }

    #[test]
    fn disambiguator_no_collision_no_suffix() {
        // No collisions → no `_2` suffix anywhere.
        let out = render_mermaid(&simple_graph(), &MermaidOptions::default());
        assert!(
            !out.contains("_2"),
            "unexpected disambiguation suffix in collision-free graph: {out}"
        );
    }

    #[test]
    fn disambiguator_handles_edges_using_disambiguated_ids() {
        // Edge endpoints must resolve through the same map as node ids
        // — otherwise edges would point at undefined / wrong nodes.
        let g = Graph {
            nodes: vec![
                Node::Service("svc".into()),
                Node::Subject("foo.*".into()),
                Node::Subject("foo.s".into()),
            ],
            edges: vec![
                Edge {
                    from: Node::Service("svc".into()),
                    to: Node::Subject("foo.*".into()),
                    kind: EdgeKind::Publish,
                    label: None,
                },
                Edge {
                    from: Node::Service("svc".into()),
                    to: Node::Subject("foo.s".into()),
                    kind: EdgeKind::Publish,
                    label: None,
                },
            ],
        };
        let out = render_mermaid(&g, &MermaidOptions::default());

        // Both subject nodes must be declared distinctly, and the two
        // Publish edges must point at the matching disambiguated ids.
        assert!(out.contains("sub_foo_s([\"foo.*\"])"));
        assert!(out.contains("sub_foo_s_2([\"foo.s\"])"));
        assert!(out.contains("--> sub_foo_s\n"));
        assert!(out.contains("--> sub_foo_s_2\n"));
    }

    #[test]
    fn disambiguator_handles_subgraph_id_collision_with_node_id() {
        // Pathological: a service named `sg_svc_x` and a publisher
        // service named `svc-x` whose subgraph id would naively also be
        // `sg_svc_x`. Disambiguator must keep them separate.
        let g = Graph {
            nodes: vec![
                Node::Service("svc-x".into()),
                Node::Service("sg_svc_x".into()),
                Node::Subject("foo".into()),
            ],
            edges: vec![Edge {
                from: Node::Service("svc-x".into()),
                to: Node::Subject("foo".into()),
                kind: EdgeKind::Publish,
                label: None,
            }],
        };
        let out = render_mermaid(&g, &MermaidOptions::default());

        // Both services + the subgraph rendered, all distinct ids.
        // Raw keys (BTreeSet order): `sg:svc-x`, `sg:__multi_publisher__`,
        // `sub:foo`, `svc:sg_svc_x`, `svc:svc-x`.
        // escape_id_basic on each:
        //   sg:svc-x          → sg_svc_x
        //   sg:__multi_pub... → sg___multi_publisher__
        //   sub:foo           → sub_foo
        //   svc:sg_svc_x      → svc_sg_svc_x
        //   svc:svc-x         → svc_svc_x
        // No collisions in this set — but the test still locks the
        // subgraph declaration uses `sg_svc_x` and the service node uses
        // `svc_sg_svc_x` (distinct prefix), proving the namespace fix.
        assert!(out.contains("subgraph sg_svc_x ["));
        assert!(out.contains("svc_sg_svc_x[\"sg_svc_x\"]"));
        assert!(out.contains("svc_svc_x[\"svc-x\"]"));
    }
}
